version: '3'

services:
  db:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DATABASE=docker_demo_development
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"

  memcached:
    image: memcached:1.5-alpine

  redis:
    image: redis:4.0-alpine

  app: &app_base
    image: parthmodi/docker_demo:latest
    environment:
      - RACK_ENV=production
      - RAILS_ENV=production
      - REDIS_CABLE_URL=redis://redis:6379/1
      - MEMCACHED_HOST=memcached
      - DB_HOST=db
      - POSTGRES_DATABASE=docker_demo_production
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - DATABASE_URL=postgres://db:5432/docker_demo_production
      - SECRET_KEY_BASE
      - VIRTUAL_HOST=docker_demo.docker
      - VIRTUAL_PORT=3000
    volumes:
      - "app-data:/home/app" 
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - memcached

  web:
    image: parthmodi/docker_nginx:latest
    links:
      - app 
    ports:
      - "8080:80"
    volumes: 
      - "app-data:/home/app"
      
volumes:
  db-data:
  app-data:
