version: '3'

services:
  db:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DATABASE=docker_demo_development
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"

  memcached:
    image: memcached:1.5-alpine

  redis:
    image: redis:4.0-alpine

  app: &app_base
    image: docker_demo:latest
    command: bundle exec rails s
    environment:
      - RACK_ENV=development
      - RAILS_ENV=development
      - REDIS_CABLE_URL=redis://redis:6379/1
      - MEMCACHED_HOST=memcached
      - DB_HOST=db
      - POSTGRES_DATABASE=docker_demo_development
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - memcached
      
volumes:
  db-data:
